general:
  use_uvloop: true

retrievers:
  statutes_retriever:
    _type: milvus_retriever
    uri: http://milvus:19530
    collection_name: "legal_statutes"
    embedding_model: milvus_embedder
    top_k: 12
  caselaw_retriever:
    _type: milvus_retriever
    uri: http://milvus:19530
    collection_name: "legal_cases"
    embedding_model: milvus_embedder
    top_k: 12

functions:
  statutes_tool:
    _type: nat_retriever
    retriever: statutes_retriever
    topic: Retrieve statutes relevant to the query
  caselaw_tool:
    _type: nat_retriever
    retriever: caselaw_retriever
    topic: Retrieve case law relevant to the query
  answer_quality_check:
    _type: llm_function
    llm_name: nim_llm
  web_search_tool:
    _type: tavily_internet_search
    max_results: 5
  aggregate_context_llm:
    _type: llm_function
    llm_name: nim_llm
    description: "Merge/dedupe Milvus+web snippets and cap tokens"

  react_agent_executor:
    _type: react_agent
    llm_name: nim_llm
    verbose: true
    tool_names:
      - statutes_tool
      - caselaw_tool
      - answer_quality_check
      - web_search_tool
      - aggregate_context_llm

ttc_strategies:
  selection_strategy:
    _type: llm_based_agent_output_merging
    selection_llm: nim_llm

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.3-70b-instruct
    temperature: 0.6
    max_tokens: 4096
    top_p: 1

embedders:
  milvus_embedder:
    _type: nim
    model_name: nvidia/nv-embedqa-e5-v5
    truncate: "END"

workflow:
  _type: execute_score_select_function
  selector: selection_strategy
  augmented_fn: react_agent_executor
  num_executions: 3
